# Default values for mlflow
replicaCount: 1

image:
  repository: burakince/mlflow
  pullPolicy: IfNotPresent
  tag: "3.4.0"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001
  fsGroupChangePolicy: "OnRootMismatch"

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

resources:
  requests:
    cpu: 300m
    memory: 1Gi
  limits:
    cpu: 1500m
    memory: 2Gi

mlflow:
  backendStore: "file:///mlflow/artifacts"
  defaultArtifactRoot: "file:///mlflow/artifacts"
  server:
    host: "0.0.0.0"
    port: 5000
    workers: 4
    maxContentLength: "100mb"
    staticPrefix: "/static"
    gunicornOptions: "--timeout 60 --keep-alive 2 --preload"

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

imagePullSecrets: []
