apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: "0.1.0"
    helm:
      values: |
        # MLflow конфігурація
        image:
          repository: burakince/mlflow
          tag: "1.25.1"
        
        # Ресурси
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        
        # Додаткові аргументи для MLflow сервера
        extraArgs:
          backend-store-uri: "sqlite:///mlflow.db"
          default-artifact-root: "/mlflow/artifacts"
        
        # Init container для встановлення MLflow в PATH
        initContainers:
          - name: setup-mlflow
            image: burakince/mlflow:1.25.1
            command: ["/bin/sh"]
            args: ["-c", "cp /mlflow/.venv/bin/mlflow /usr/local/bin/mlflow"]
            volumeMounts:
              - name: mlflow-bin
                mountPath: /usr/local/bin
        extraVolumes:
          - name: mlflow-bin
            emptyDir: {}
          - name: mlflow-data
            emptyDir: {}
        extraVolumeMounts:
          - name: mlflow-bin
            mountPath: /usr/local/bin
          - name: mlflow-data
            mountPath: /mlflow
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true