apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: "1.7.1"
    helm:
      values: |
        # MLflow конфігурація - GitOps демонстрація v8.0 (ТЕСТ: масштабування)
        replicaCount: 3
        
        image:
          repository: burakince/mlflow
          tag: "latest"
        
        # Ресурси (оновлено v8.0 - зменшені для тестування масштабування)
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        
        # Налаштування сервісу
        service:
          type: ClusterIP
          port: 80
        
        # Налаштування здоров'я (оновлено - швидші перевірки)
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true