apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: "1.7.1"
    helm:
      values: |
        # MLflow конфігурація - GitOps Variant A (inline values)
        image:
          repository: burakince/mlflow
          tag: "3.4.0"
        
        # Ресурси (GitOps демонстрація v6.0 - оновлення ресурсів)
        resources:
          requests:
            cpu: 600m
            memory: 1.2Gi
          limits:
            cpu: 2500m
            memory: 2.5Gi
        
        # Налаштування сервісу
        service:
          type: ClusterIP
          port: 80
        
        # Налаштування здоров'я
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true