# MLflow Helm values
# Використовуємо готовий чарт з community-charts

# Кількість реплік
replicaCount: 1

# Образ контейнера
image:
  repository: burakince/mlflow
  tag: "3.4.0"
  pullPolicy: IfNotPresent

# Ресурси для MLflow (v2.3)
resources:
  requests:
    cpu: 600m
    memory: 2Gi
  limits:
    cpu: 2500m
    memory: 4Gi

# Налаштування сервісу
service:
  type: ClusterIP
  port: 80
  targetPort: 5000

# Налаштування здоров'я
livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
