# MLflow конфігурація для GitOps
image:
  repository: burakince/mlflow
  tag: "3.4.0"

# Ресурси (оптимальні для MLflow)
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

# Налаштування сервісу
service:
  type: ClusterIP
  port: 80

# Налаштування здоров'я
livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
