apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Olekstar/goit-argo.git
    path: .
    targetRevision: working-structure
    helm:
      values: |
        # MLflow конфігурація - GitOps демонстрація v7.0
        image:
          repository: burakince/mlflow
          tag: "3.5.0"
        
        # Ресурси (оновлено v7.0 - збільшені ресурси)
        resources:
          requests:
            cpu: 500m
            memory: 1.5Gi
          limits:
            cpu: 2500m
            memory: 3Gi
        
        # Налаштування сервісу
        service:
          type: ClusterIP
          port: 80
          targetPort: 5000
        
        # Налаштування здоров'я
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true