apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: "1.7.1"
    helm:
      values: |
        # MLflow конфігурація - використовуємо готовий чарт з ArtifactHub
        image:
          repository: burakince/mlflow
          tag: "3.4.0"
        
        # Приклад: збільшуємо ресурси
        # resources:
        #   requests:
        #     cpu: 300m
        #     memory: 1Gi
        #   limits:
        #     cpu: 1500m
        #     memory: 2Gi
        
        # Ресурси
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true